name: Trigger Workflows

on:
    workflow_run:
        workflows: ["tty-ov-pypi", "tty-ov-gh-packages"]
        types:
            - completed
    workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Check tty-ov-pypi Status
      if: github.event.workflow_run.conclusion != 'success'
      run: |
        echo "Workflow1 failed, not triggering Workflow2"
        exit 1
